[[shades]]
name = "vibrance"
default = true  # shader to use during times when there is no other shader scheduled

# [[shades]]
# name = "redshift"
# start_time = 19:00:00
# end_time = 06:00:00   # optional if you have more than one shade with start_time
